### ISSUE TITLE
Duplicated example in plotsjl-cheatsheet.pdf?

### ISSUE THREAD

**Issue by wongjoel** [sswatson/cheatsheets#1]
Thanks for making these great cheatsheets.

In plotsjl-cheatsheet.pdf, the examples illustrating the different series types show exactly the examples for `:line` and `:path` twice. Just checking if that was the intent?

**Comment by sswatson** [comment]
Thanks! Fixed in f0f94a7c9f4442c6e4f852dfad19246cc916e205.
