### ISSUE TITLE
Add translation?

### ISSUE THREAD

**Issue by kagalenko-m-b** [sswatson/cheatsheets#2]
Hello, I would like to add Russian translation to your valuable Plots.jl cheatsheet. Any chance you could share the source so I could edit the text? Thanks.

**Comment by sswatson** [comment]
Yes, no problem.

Given the nature of LaTeX, I suspect that an Overleaf link would be easier to use than files and instructions to replicate my environment:

[https://www.overleaf.com/read/kvmwvcyfkqqq](https://www.overleaf.com/read/kvmwvcyfkqqq)

You can make a copy in Overleaf and edit it there, or you can copy all of the files and use them to set up a local installation.
